stages:
  - stage: PreDeployment
    jobs:
      - job: Code_Validation
        steps:
          - script: |
              docker pull github/super-linter:latest
            displayName: Pull github/super-linter docker image

          - script: |
              docker run \
                -e RUN_LOCAL=true \
                -e VALIDATE_ARM=true \
                -v $(System.DefaultWorkingDirectory):/tmp/lint \
                github/super-linter
            displayName: super-linter validation